### PR TITLE
Better error messages

### LINKED ISSUE #41: Improve error & warning messages
https://wix-ux.com/when-life-gives-you-lemons-write-better-error-messages-46c5223e1a2f

Do a better job at reporting when things go wrong. Also have a mechanism to easily emit warnings/errors & give users useful CTA to recover.

### PR DESCRIPTION
**Pull request by nicoespeon**
Closes #41 

The main change is that "error" isn't a state anymore, but an optional attribute of a Conversation. That way, we can show the error at the bottom of the conversation instead of replacing the whole thing (after a few experimentations, it felt to be the best alternative)

| Simple Error | Detailed Error |
|---|---|
| simpler error | error |

The "Dismiss" button clears the error. For detailed errors, it's possible to disable the Dismiss button, the Retry button, or both. The layout will adapt.

no retry

I also made it possible for detailed errors to be "warnings". It makes more sense when you want to report something to the user, but there is no need to retry. For instance:

warning level

But I still don't have a strong opinion on this. Feel free to iterate on that. 
Same story for the design: I went for something that looks better, but is not too fancy. Feel free to make updates.

Other things:
- Detailed errors support Markdown in title & message
- Errors can be triggered from any conversation… but there is no "top-level" error yet. 

I have only ported the "syntax highlight" error so far. But with the system in place, we will be able to port more!

### CODE REVIEW

File: lib/webview/src/component/DiffView.tsx [hunk 1]
```diff
@@ -318,9 +319,15 @@ function toPrismHighlightOptions(
...
 
     default:
-      console.warn(
-        `Can't find Prism grammar for language ${languageId}, use default one`
-      );
+      sendMessage({
+        type: "showError",
+        error: {
+          title: `Unable to highlight syntax for language ${languageId}`,
+          message: `We could not find a matching Prism grammar for language ${languageId}. We used the default one (${DEFAULT_PRISM_OPTIONS.language}). Please [open an issue](https://github.com/rubberduck-ai/rubberduck-vscode/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Add%20syntax%20highlight%20for%20language%20%22${languageId}%22) to ask for supporting this language.`,
```
Comment (nicoespeon) [inline lib/webview/src/component/DiffView.tsx:326]: This would create a link that works to create a new GitHub issue, like this: https://github.com/rubberduck-ai/rubberduck-vscode/issues/new?assignees=&labels=enhancement&template=feature_request.md&title=Add%20syntax%20highlight%20for%20language%20%22typescript%22

IMO, this is useful for error messages that we create. It will simplify reporting errors since we could also include content in the body (eg. `&body=${encodeURIComponent(error)}`)

File: lib/common/src/webview-api/ErrorSchema.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
+import zod from "zod";
+
+export const errorSchema = zod.union([
+  zod.string(),
+  zod.object({
+    title: zod.string(),
+    message: zod.string(),
+    level: zod.union([zod.literal("error"), zod.literal("warning")]).optional(),
```
Comment (lgrammel) [inline lib/common/src/webview-api/ErrorSchema.ts:8]: Defaults to error.

File: lib/common/src/webview-api/ErrorSchema.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+    disableDismiss: zod.boolean().optional(),
+  }),
+]);
+
+/**
+ * Say what happened.
+ * Provide re-assurance and explain why it happened. Suggest actions
+ * to help them fix it and/or give them a way out.
+ *
+ * You can use Markdown syntax.
```
Comment (lgrammel) [inline lib/common/src/webview-api/ErrorSchema.ts:19]: for title and message

File: lib/common/src/webview-api/OutgoingMessage.ts [hunk 4]
```diff
@@ -26,6 +27,16 @@ export const outgoingMessageSchema = zod.discriminatedUnion("type", [
       message: zod.string(),
     }),
   }),
+  zod.object({
+    type: zod.literal("showError"),
```
Comment (lgrammel) [inline lib/common/src/webview-api/OutgoingMessage.ts:31]: reportError

File: lib/extension/src/chat/ChatController.ts [hunk 5]
```diff
@@ -98,9 +98,18 @@ export class ChatController {
...
+      case "dismissError":
+        await this.chatModel
+          .getConversationById(message.data.id)
+          ?.dismissError();
+        break;
       case "applyDiff": {
         break;
       }
+      case "showError": {
+        await this.showError(message.error);
```
Comment (lgrammel) [inline lib/extension/src/chat/ChatController.ts:110]: setErrorOnSelectedConversation?

File: lib/extension/src/chat/ChatController.ts [hunk 6]
```diff
@@ -153,4 +162,12 @@ export class ChatController {
       await vscode.window.showErrorMessage(error?.message ?? error);
     }
   }
+
+  private async showError(error: webviewApi.Error) {
+    const conversation = this.chatModel.getSelectedConversation();
+    if (!conversation) return;
+
+    await this.showChatPanel();
+    conversation.setError(error);
```
[the remark this answers is not in the document]
Comment (lgrammel) [reply lib/extension/src/chat/ChatController.ts:171]: Move into model?

File: lib/extension/src/chat/ChatController.ts (hunk 5 above)
Comment (lgrammel) [reply lib/extension/src/chat/ChatController.ts:110]: may not be used?

File: lib/extension/src/chat/ChatController.ts [hunk 7]
```diff
@@ -98,9 +98,18 @@ export class ChatController {
         await this.chatModel.getConversationById(message.data.id)?.retry();
         break;
       }
+      case "dismissError":
+        await this.chatModel
+          .getConversationById(message.data.id)
+          ?.dismissError();
+        break;
       case "applyDiff": {
         break;
```
Comment (lgrammel) [inline lib/extension/src/chat/ChatController.ts:107]: architecture debt because there are 2 views, but only 1 outgoing message type

File: lib/webview/src/component/ErrorMessage.tsx [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+      <div className="error-buttons">
+        {!error.disableDismiss && (
+          <button className="error-dismiss" onClick={onClickDismiss}>
+            Dismiss
+          </button>
+        )}
+        {!error.disableRetry && (
+          <button className="error-retry" onClick={onClickRetry}>
+            <i className="codicon codicon-debug-restart inline" />
+            <span style={{ marginLeft: "5px" }}>Retry</span>
```
Comment (lgrammel) [inline lib/webview/src/component/ErrorMessage.tsx:39]: Maybe tweak .codicon.inline to add a margin right
Also, there is some minor duplication

**Review by lgrammel — APPROVED** [review]
